repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml

  - repo: local
    hooks:
      - id: gradle-test
        name: Gradle test
        entry: ./gradlew test
        language: system
        pass_filenames: false
